version: "3.8"
services:
  db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: on-failure

volumes:
  db_data: